/**
 * Colors of Material Design Tokens 3 generated with https://material-foundation.github.io/material-theme-builder/ (seed purple color #CE5BD6)
 */

export type Theme = {
	primary: string
	onPrimary: string
	primaryContainer: string
	onPrimaryContainer: string
	secondary: string
	onSecondary: string
	secondaryContainer: string
	onSecondaryContainer: string
	tertiary: string
	onTertiary: string
	tertiaryContainer: string
	onTertiaryContainer: string
	error: string
	onError: string
	errorContainer: string
	onErrorContainer: string
	background: string
	onBackground: string
	surface: string
	onSurface: string
	surfaceVariant: string
	onSurfaceVariant: string
	outline: string
	outlineVariant: string
	shadow: string
	scrim: string
	inverseSurface: string
	inverseOnSurface: string
	inversePrimary: string
	primaryFixed: string
	onPrimaryFixed: string
	primaryFixedDim: string
	onPrimaryFixedVariant: string
	secondaryFixed: string
	onSecondaryFixed: string
	secondaryFixedDim: string
	onSecondaryFixedVariant: string
	tertiaryFixed: string
	onTertiaryFixed: string
	tertiaryFixedDim: string
	onTertiaryFixedVariant: string
	surfaceDim: string
	surfaceBright: string
	surfaceContainerLowest: string
	surfaceContainerLow: string
	surfaceContainer: string
	surfaceContainerHigh: string
	surfaceContainerHighest: string
	surfaceTint: string
}

export const themeLight: Theme = {
	primary: '#7D4E7D',
	onPrimary: '#FFFFFF',
	primaryContainer: '#FFD6FA',
	onPrimaryContainer: '#633664',
	secondary: '#6C586A',
	onSecondary: '#FFFFFF',
	secondaryContainer: '#F5DBF0',
	onSecondaryContainer: '#534152',
	tertiary: '#825248',
	onTertiary: '#FFFFFF',
	tertiaryContainer: '#FFDAD3',
	onTertiaryContainer: '#673B32',
	error: '#BA1A1A',
	onError: '#FFFFFF',
	errorContainer: '#FFDAD6',
	onErrorContainer: '#93000A',
	background: '#FFF7FA',
	onBackground: '#1F1A1F',
	surface: '#FFF7FA',
	onSurface: '#1F1A1F',
	surfaceVariant: '#EDDEE8',
	onSurfaceVariant: '#4D444C',
	outline: '#7F747C',
	outlineVariant: '#D0C3CC',
	shadow: '#000000',
	scrim: '#000000',
	inverseSurface: '#352E34',
	inverseOnSurface: '#F9EDF4',
	inversePrimary: '#EDB4EA',
	primaryFixed: '#FFD6FA',
	onPrimaryFixed: '#320936',
	primaryFixedDim: '#EDB4EA',
	onPrimaryFixedVariant: '#633664',
	secondaryFixed: '#F5DBF0',
	onSecondaryFixed: '#261625',
	secondaryFixedDim: '#D8BFD4',
	onSecondaryFixedVariant: '#534152',
	tertiaryFixed: '#FFDAD3',
	onTertiaryFixed: '#33110B',
	tertiaryFixedDim: '#F6B8AB',
	onTertiaryFixedVariant: '#673B32',
	surfaceDim: '#E2D7DE',
	surfaceBright: '#FFF7FA',
	surfaceContainerLowest: '#FFFFFF',
	surfaceContainerLow: '#FCF0F7',
	surfaceContainer: '#F6EBF1',
	surfaceContainerHigh: '#F1E5EC',
	surfaceContainerHighest: '#EBDFE6',
	surfaceTint: '#7D4E7D',
} as const

export const themeLightMediumContrast: Theme = {
	primary: '#502652',
	onPrimary: '#FFFFFF',
	primaryContainer: '#8D5C8D',
	onPrimaryContainer: '#FFFFFF',
	secondary: '#423141',
	onSecondary: '#FFFFFF',
	secondaryContainer: '#7B6779',
	onSecondaryContainer: '#FFFFFF',
	tertiary: '#532B23',
	onTertiary: '#FFFFFF',
	tertiaryContainer: '#926056',
	onTertiaryContainer: '#FFFFFF',
	error: '#740006',
	onError: '#FFFFFF',
	errorContainer: '#CF2C27',
	onErrorContainer: '#FFFFFF',
	background: '#FFF7FA',
	onBackground: '#1F1A1F',
	surface: '#FFF7FA',
	onSurface: '#151014',
	surfaceVariant: '#EDDEE8',
	onSurfaceVariant: '#3C343B',
	outline: '#595057',
	outlineVariant: '#756A72',
	shadow: '#000000',
	scrim: '#000000',
	inverseSurface: '#352E34',
	inverseOnSurface: '#F9EDF4',
	inversePrimary: '#EDB4EA',
	primaryFixed: '#8D5C8D',
	onPrimaryFixed: '#FFFFFF',
	primaryFixedDim: '#724473',
	onPrimaryFixedVariant: '#FFFFFF',
	secondaryFixed: '#7B6779',
	onSecondaryFixed: '#FFFFFF',
	secondaryFixedDim: '#624F60',
	onSecondaryFixedVariant: '#FFFFFF',
	tertiaryFixed: '#926056',
	onTertiaryFixed: '#FFFFFF',
	tertiaryFixedDim: '#77493F',
	onTertiaryFixedVariant: '#FFFFFF',
	surfaceDim: '#CEC3CA',
	surfaceBright: '#FFF7FA',
	surfaceContainerLowest: '#FFFFFF',
	surfaceContainerLow: '#FCF0F7',
	surfaceContainer: '#F1E5EC',
	surfaceContainerHigh: '#E5DAE0',
	surfaceContainerHighest: '#DACFD5',
	surfaceTint: '#7D4E7D',
} as const

export const themeLightHighContrast: Theme = {
	primary: '#451B48',
	onPrimary: '#FFFFFF',
	primaryContainer: '#663967',
	onPrimaryContainer: '#FFFFFF',
	secondary: '#372737',
	onSecondary: '#FFFFFF',
	secondaryContainer: '#564354',
	onSecondaryContainer: '#FFFFFF',
	tertiary: '#47211A',
	onTertiary: '#FFFFFF',
	tertiaryContainer: '#693E34',
	onTertiaryContainer: '#FFFFFF',
	error: '#600004',
	onError: '#FFFFFF',
	errorContainer: '#98000A',
	onErrorContainer: '#FFFFFF',
	background: '#FFF7FA',
	onBackground: '#1F1A1F',
	surface: '#FFF7FA',
	onSurface: '#000000',
	surfaceVariant: '#EDDEE8',
	onSurfaceVariant: '#000000',
	outline: '#322A31',
	outlineVariant: '#50464E',
	shadow: '#000000',
	scrim: '#000000',
	inverseSurface: '#352E34',
	inverseOnSurface: '#FFFFFF',
	inversePrimary: '#EDB4EA',
	primaryFixed: '#663967',
	onPrimaryFixed: '#FFFFFF',
	primaryFixedDim: '#4C224F',
	onPrimaryFixedVariant: '#FFFFFF',
	secondaryFixed: '#564354',
	onSecondaryFixed: '#FFFFFF',
	secondaryFixedDim: '#3E2D3D',
	onSecondaryFixedVariant: '#FFFFFF',
	tertiaryFixed: '#693E34',
	onTertiaryFixed: '#FFFFFF',
	tertiaryFixedDim: '#4F2820',
	onTertiaryFixedVariant: '#FFFFFF',
	surfaceDim: '#C0B6BC',
	surfaceBright: '#FFF7FA',
	surfaceContainerLowest: '#FFFFFF',
	surfaceContainerLow: '#F9EDF4',
	surfaceContainer: '#EBDFE6',
	surfaceContainerHigh: '#DDD1D8',
	surfaceContainerHighest: '#CEC3CA',
	surfaceTint: '#7D4E7D',
} as const

export const themeDark: Theme = {
	primary: '#EDB4EA',
	onPrimary: '#4A204C',
	primaryContainer: '#633664',
	onPrimaryContainer: '#FFD6FA',
	secondary: '#D8BFD4',
	onSecondary: '#3C2B3B',
	secondaryContainer: '#534152',
	onSecondaryContainer: '#F5DBF0',
	tertiary: '#F6B8AB',
	onTertiary: '#4C261E',
	tertiaryContainer: '#673B32',
	onTertiaryContainer: '#FFDAD3',
	error: '#FFB4AB',
	onError: '#690005',
	errorContainer: '#93000A',
	onErrorContainer: '#FFDAD6',
	background: '#171216',
	onBackground: '#EBDFE6',
	surface: '#171216',
	onSurface: '#EBDFE6',
	surfaceVariant: '#4D444C',
	onSurfaceVariant: '#D0C3CC',
	outline: '#998D96',
	outlineVariant: '#4D444C',
	shadow: '#000000',
	scrim: '#000000',
	inverseSurface: '#EBDFE6',
	inverseOnSurface: '#352E34',
	inversePrimary: '#7D4E7D',
	primaryFixed: '#FFD6FA',
	onPrimaryFixed: '#320936',
	primaryFixedDim: '#EDB4EA',
	onPrimaryFixedVariant: '#633664',
	secondaryFixed: '#F5DBF0',
	onSecondaryFixed: '#261625',
	secondaryFixedDim: '#D8BFD4',
	onSecondaryFixedVariant: '#534152',
	tertiaryFixed: '#FFDAD3',
	onTertiaryFixed: '#33110B',
	tertiaryFixedDim: '#F6B8AB',
	onTertiaryFixedVariant: '#673B32',
	surfaceDim: '#171216',
	surfaceBright: '#3E373C',
	surfaceContainerLowest: '#120D11',
	surfaceContainerLow: '#1F1A1F',
	surfaceContainer: '#241E23',
	surfaceContainerHigh: '#2E282D',
	surfaceContainerHighest: '#393338',
	surfaceTint: '#EDB4EA',
} as const

export const themeDarkMediumContrast: Theme = {
	primary: '#FFCDFB',
	onPrimary: '#3E1441',
	primaryContainer: '#B47FB2',
	onPrimaryContainer: '#000000',
	secondary: '#EFD5EA',
	onSecondary: '#302030',
	secondaryContainer: '#A18A9D',
	onSecondaryContainer: '#000000',
	tertiary: '#FFD2C9',
	onTertiary: '#3F1B14',
	tertiaryContainer: '#BA8378',
	onTertiaryContainer: '#000000',
	error: '#FFD2CC',
	onError: '#540003',
	errorContainer: '#FF5449',
	onErrorContainer: '#000000',
	background: '#171216',
	onBackground: '#EBDFE6',
	surface: '#171216',
	onSurface: '#FFFFFF',
	surfaceVariant: '#4D444C',
	onSurfaceVariant: '#E7D8E2',
	outline: '#BBAEB7',
	outlineVariant: '#998D96',
	shadow: '#000000',
	scrim: '#000000',
	inverseSurface: '#EBDFE6',
	inverseOnSurface: '#2E282D',
	inversePrimary: '#643865',
	primaryFixed: '#FFD6FA',
	onPrimaryFixed: '#25002A',
	primaryFixedDim: '#EDB4EA',
	onPrimaryFixedVariant: '#502652',
	secondaryFixed: '#F5DBF0',
	onSecondaryFixed: '#1A0C1B',
	secondaryFixedDim: '#D8BFD4',
	onSecondaryFixedVariant: '#423141',
	tertiaryFixed: '#FFDAD3',
	onTertiaryFixed: '#250703',
	tertiaryFixedDim: '#F6B8AB',
	onTertiaryFixedVariant: '#532B23',
	surfaceDim: '#171216',
	surfaceBright: '#494248',
	surfaceContainerLowest: '#0A060A',
	surfaceContainerLow: '#211C21',
	surfaceContainer: '#2C262B',
	surfaceContainerHigh: '#373136',
	surfaceContainerHighest: '#423C41',
	surfaceTint: '#EDB4EA',
} as const

export const themeDarkHighContrast: Theme = {
	primary: '#FFEAFA',
	onPrimary: '#000000',
	primaryContainer: '#E9B0E6',
	onPrimaryContainer: '#1B001F',
	secondary: '#FFEAFA',
	onSecondary: '#000000',
	secondaryContainer: '#D4BBD0',
	onSecondaryContainer: '#140614',
	tertiary: '#FFECE8',
	onTertiary: '#000000',
	tertiaryContainer: '#F1B4A7',
	onTertiaryContainer: '#1D0301',
	error: '#FFECE9',
	onError: '#000000',
	errorContainer: '#FFAEA4',
	onErrorContainer: '#220001',
	background: '#171216',
	onBackground: '#EBDFE6',
	surface: '#171216',
	onSurface: '#FFFFFF',
	surfaceVariant: '#4D444C',
	onSurfaceVariant: '#FFFFFF',
	outline: '#FBECF6',
	outlineVariant: '#CCBFC8',
	shadow: '#000000',
	scrim: '#000000',
	inverseSurface: '#EBDFE6',
	inverseOnSurface: '#000000',
	inversePrimary: '#643865',
	primaryFixed: '#FFD6FA',
	onPrimaryFixed: '#000000',
	primaryFixedDim: '#EDB4EA',
	onPrimaryFixedVariant: '#25002A',
	secondaryFixed: '#F5DBF0',
	onSecondaryFixed: '#000000',
	secondaryFixedDim: '#D8BFD4',
	onSecondaryFixedVariant: '#1A0C1B',
	tertiaryFixed: '#FFDAD3',
	onTertiaryFixed: '#000000',
	tertiaryFixedDim: '#F6B8AB',
	onTertiaryFixedVariant: '#250703',
	surfaceDim: '#171216',
	surfaceBright: '#554E53',
	surfaceContainerLowest: '#000000',
	surfaceContainerLow: '#241E23',
	surfaceContainer: '#352E34',
	surfaceContainerHigh: '#40393F',
	surfaceContainerHighest: '#4C454A',
	surfaceTint: '#EDB4EA',
} as const

type ThemeNames =
	| 'light'
	| 'light-medium-contrast'
	| 'light-high-contrast'
	| 'dark'
	| 'dark-medium-contrast'
	| 'dark-high-contrast'

export const themes: Record<ThemeNames, Theme> = {
	light: themeLight,
	'light-medium-contrast': themeLightMediumContrast,
	'light-high-contrast': themeLightHighContrast,
	dark: themeDark,
	'dark-medium-contrast': themeDarkMediumContrast,
	'dark-high-contrast': themeDarkHighContrast,
} as const
